"""added disconnected

Revision ID: 23e4f0388650
Revises: 9797ac5db446
Create Date: 2024-05-01 08:24:45.186803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23e4f0388650'
down_revision: Union[str, None] = '9797ac5db446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('disconnected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'disconnected')
    # ### end Alembic commands ###
