"""Your message

Revision ID: 9797ac5db446
Revises: e6d1cd0516c2
Create Date: 2024-04-30 21:16:28.937475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9797ac5db446'
down_revision: Union[str, None] = 'e6d1cd0516c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('latest_messagee', sa.DateTime(), nullable=True))
    op.drop_column('users', 'latest_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('latest_message', sa.TIME(), nullable=True))
    op.drop_column('users', 'latest_messagee')
    # ### end Alembic commands ###
